### PR TITLE
WiP patch for a salted codespeed instance

### PR DESCRIPTION
**Pull request by zware**

### CODE REVIEW

**Comment by zware** [comment]
Using pycon for a guide, I was able to get things to the point they are in this PR, and things seem to work for the most part.  I'd appreciate some review and help from the more knowledgable to smooth out the rough spots, most of which are marked by comments.

**Comment by gutworth** [comment]
I'm sorry this took way too long. It looks pretty good.

**Comment by holdenweb** [comment]
FFS, you are a volunteer. Stop apologising!

**Comment by zware** [comment]
A little stronger than I'd word it, but agreed :).  Thanks for the merge!

**Pull request merged**
