### PR TITLE
Move bugs.python.org IRC notifications to Libera Chat

### PR DESCRIPTION
**Pull request by vstinner**

### CODE REVIEW

**Review by pablogsal — APPROVED** [review]
LGTM

**Comment by vstinner** [comment]
cc @ewdurbin

**Comment by zware** [comment]
LGTM, but we may run into the same SASL issues here as we did with buildbot.  The somewhat hacky solution I have in place there is to run a [znc](https://wiki.znc.in/ZNC) bouncer on the buildbot host.

**Comment by ewdurbin** [comment]
let's give it a shot.

**Comment by ewdurbin** [comment]
> LGTM, but we may run into the same SASL issues here as we did with buildbot. The somewhat hacky solution I have in place there is to run a [znc](https://wiki.znc.in/ZNC) bouncer on the buildbot host.

Is intended to be a durable solution? If so we should actually add it to the buildbot salt configuration. Otherwise it will be lost in the event of a server failure and recovery from backup scenario.

**Comment by ewdurbin** [comment]
Tried to validate that this change did anything but not sure how to 😂

I don't see any errors in irker's log though.

**Pull request merged**
