### PR TITLE
feat(#528): allow `roundup` group users to interact with git repos

### LINKED ISSUE #528: Allow `roundup` group to interact with tracker config clones set by Salt
See if there’s a way to get the permissions set by salt to allow users in the `roundup` group to interact with the clones of tracker configs?

[Slack Message](https://thepsf.slack.com/archives/C09FH6L0P/p1732116150102499)

### PR DESCRIPTION
**Pull request by JacobCoffee**
## Description

- Adds group write bit for cloned repos 

## Closes

- Closes #528

### CODE REVIEW

**Comment by JacobCoffee** [comment]
@ewdurbin wdyt? will this be sufficient or did I misunderstand maybe?

**Comment by ewdurbin** [comment]
I'm not entirely sure. The goal is that the following would work without error, note that `rouilj` is a member of the roundup group.

```
ee@bugs:~$ sudo su - rouilj 
rouilj@bugs:/srv/roundup/trackers/cpython$ groups
rouilj psf-admin roundup
rouilj@bugs:~$ cd /srv/roundup/trackers/cpython/
rouilj@bugs:/srv/roundup/trackers/cpython$ git status
fatal: detected dubious ownership in repository at '/srv/roundup/trackers/cpython'
To add an exception for this directory, call:

	git config --global --add safe.directory /srv/roundup/trackers/cpython
```

This should be reproducible locally for verification.

**Comment by ewdurbin** [comment]
Testing, it doesn't look like this resolves the issue when bringing up the service locally.

**Comment by JacobCoffee** [comment]
This seems to work–I misunderstood what was needing done

```
vagrant@bugs:~$ sudo su coffee
coffee@bugs:/home/vagrant$ sudo su - rouilj 
rouilj@bugs:~$ cd /srv/roundup/trackers/cpython/
rouilj@bugs:/srv/roundup/trackers/cpython$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        config.ini
        detectors/config.ini
        django-gae2django/
        rietveld/
        scripts/suggest.pyc
        wsgi.py
        wsgi.pyc

nothing added to commit but untracked files present (use "git add" to track)
rouilj@bugs:/srv/roundup/trackers/cpython$ cat /etc/gitconfig 
# TRACKER-cpython-START
[safe]
directory = /srv/roundup/trackers/cpython
# TRACKER-cpython-END
# TRACKER-jython-START
[safe]
directory = /srv/roundup/trackers/jython
# TRACKER-jython-END
# TRACKER-roundup-START
[safe]
directory = /srv/roundup/trackers/roundup
# TRACKER-roundup-END
```

**Review by ewdurbin — APPROVED** [review]
good to go once the linting passes!

**Pull request merged**
