### PR TITLE
GNU Terry Pratchett

### PR DESCRIPTION
**Pull request by ncoghlan**
http://gnuterrypratchett.com/

### CODE REVIEW

**Comment by ncoghlan** [comment]
I couldn't find any clear docs on hardcoding a header in HAProxy, so the double quoted string is an assumption.

**Comment by dstufft** [comment]
Hm, I'm not sure if it needs quotes or not. I'll test it locally in Vagrant before merge.

**Comment by dstufft** [comment]
Deployed:

```console
$ curl -I https://hg.python.org/ -s
HTTP/1.1 200 Script output follows
Date: Thu, 19 Mar 2015 06:14:16 GMT
Server: Apache/2.4.7 (Ubuntu)
Vary: Accept-Encoding
Content-Type: text/html; charset=utf-8
X-Clacks-Overhead: GNU Terry Pratchett
Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
Public-Key-Pins: max-age=2592000; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU="; pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI="; pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";
```

**Comment by holdenweb** [comment]
I was wondering whether we could also add the recently-deceased John Pinner, one of the long-time leaders of the Python UK community, who died recently. That's a name that should live on.  S

On Mar 19, 2015, at 5:10 AM, ncoghlan <notifications@github.com> wrote:

> http://gnuterrypratchett.com/
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/python/psf-salt/pull/41
> 
> Commit Summary
> 
> GNU Terry Pratchett
> File Changes
> 
> M salt/haproxy/config/haproxy.cfg.jinja (3)
> Patch Links:
> 
> https://github.com/python/psf-salt/pull/41.patch
> https://github.com/python/psf-salt/pull/41.diff
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Steve Holden steve@holdenweb.com / +1 571 484 6266 / +44 113 320 2335 / @holdenweb

**Comment by dstufft** [comment]
Hey Steve,

I don't want to start a precedence here for memorializing Python community members in the headers of our site. Not that they don't deserve to be memorialized but that I think it's better if that is done by the individual Python organizations who know them best and who they were a part of. In addition, we can only have so many headers (most HTTP clients have some common sense limits) so at some point we'd have to stop putting names in the headers and I feel like that could cause a lot of hurt feelings whenever we'd be forced to draw a somewhat arbitrary line in the sand about when we can accept no more names (or worse, have to decide whose name we remove).

**Comment by Lukasa** [comment]
Following up on what @dstufft said, we should do it in the UK. I think the PyCon UK Committee should add the equivalent header to their properties. =) I'll ping some people and see if we can get the ball rolling.

**Comment by ntoll** [comment]
I've been pinged by @Lukasa and will mention it in the appropriate PyconUK related mailing list.

**Comment by holdenweb** [comment]
Understood. Thanks.  S

On Mar 19, 2015, at 9:29 AM, Donald Stufft <notifications@github.com> wrote:

> Hey Steve,
> 
> I don't want to start a precedence here for memorializing Python community members in the headers of our site. Not that they don't deserve to be memorialized but that I think it's better if that is done by the individual Python organizations who know them best and who they were a part of. In addition, we can only have so many headers (most HTTP clients have some common sense limits) so at some point we'd have to stop putting names in the headers and I feel like that could cause a lot of hurt feelings whenever we'd be forced to draw a somewhat arbitrary line in the sand about when we can accept no more names (or worse, have to decide whose name we remove).
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Steve Holden steve@holdenweb.com / +1 571 484 6266 / +44 113 320 2335 / @holdenweb

**Pull request merged**
