### PR TITLE
Versionning and documenting our ssh_known_hosts file.

### PR DESCRIPTION
**Pull request by JulienPalard**
https://github.com/python/psf-salt/issues/104

### CODE REVIEW

**Comment by ewdurbin** [comment]
@JulienPalard Thank you! I'm going to double check the generation script on my host (MacOS), as long as that works, this is 💯

**Comment by ewdurbin** [comment]
@JulienPalard my output doesn't seem complete :/

```
# consul0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# consul2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# lb2.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# mail.python.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# mail.python.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# mail.python.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# monitoring.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# monitoring.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# monitoring.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# monitoring.pypi.io:22 SSH-2.0-OpenSSH_5.3
# monitoring.pypi.io:22 SSH-2.0-OpenSSH_5.3
# monitoring.pypi.io:22 SSH-2.0-OpenSSH_5.3
# pg0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pg0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pg0.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pg1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pg1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pg1.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# planet.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# planet.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# planet.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-prod.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-prod.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-prod.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-staging.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-staging.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pydotorg-staging.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# pythontest.nyc1.psf.io:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
# pythontest.nyc1.psf.io:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
# pythontest.nyc1.psf.io:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2
# slack.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# slack.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# slack.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# speed-web.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# speed-web.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# speed-web.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# web0.pypa.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# web0.pypa.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# web0.pypa.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# web0.pypi.io:22 SSH-2.0-OpenSSH_5.3
# web0.pypi.io:22 SSH-2.0-OpenSSH_5.3
# web0.pypi.io:22 SSH-2.0-OpenSSH_5.3
# web1.pypi.io:22 SSH-2.0-OpenSSH_5.3
# web1.pypi.io:22 SSH-2.0-OpenSSH_5.3
# web1.pypi.io:22 SSH-2.0-OpenSSH_5.3
# evote.python.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.4
# evote.python.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.4
# evote.python.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.4
# virt-h669vt.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# virt-h669vt.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# virt-h669vt.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# speed-python.osuosl.org:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# speed-python.osuosl.org:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# speed-python.osuosl.org:22 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
virt-wzmlmm.psf.osuosl.org: Connection closed by remote host
virt-wzmlmm.psf.osuosl.org: Connection closed by remote host
virt-wzmlmm.psf.osuosl.org: Connection closed by remote host
# virt-gwhg4e.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-gwhg4e.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-gwhg4e.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-ys0nco.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-ys0nco.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-ys0nco.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.10
# virt-et2yi0.psf.osuosl.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# virt-et2yi0.psf.osuosl.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# virt-et2yi0.psf.osuosl.org:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# virt-wdiwcy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-wdiwcy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-wdiwcy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-sxw5uy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# virt-sxw5uy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# virt-sxw5uy.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1.7
# virt-k4b2sa.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-k4b2sa.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-k4b2sa.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-8joqck.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-8joqck.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-8joqck.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-7tac5q.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-7tac5q.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
# virt-7tac5q.psf.osuosl.org:22 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
virt-l99amx.psf.osuosl.org: Connection closed by remote host
virt-l99amx.psf.osuosl.org: Connection closed by remote host
140.211.10.67: Connection closed by remote host
140.211.10.67: Connection closed by remote host
140.211.10.67: Connection closed by remote host
virt-l99amx.psf.osuosl.org: Connection closed by remote host
140.211.10.83: Connection closed by remote host
140.211.10.83: Connection closed by remote host
140.211.10.83: Connection closed by remote host
virt-7tac5q.psf.osuosl.org,140.211.10.82 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDEraq+pgWRiuW0TEay8UHmtNdbVy7QsIK9NJAuhI57PrV//24E+jHIcN58oNyY2XSEf8aivCjVDVBzCMNGC1oI=
virt-7tac5q.psf.osuosl.org,140.211.10.82 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/eJNqqvNHPZ8IxcB+jZmOJr589Bjj4UytVv5CQvK2lp13JYYoY64+ml2o6amz4siqOMDcZhKTnJjDjFKi4vP/H4j2Tb4XK9C1yH8MS13szj9F3yP24hijB7x25FUOSG2hHgfZlvFaqqrIe8skTeAb+k8xhAag6EvyUWBSgRyp1erBSni0mWBmWoTcClJRti5RFgyrmYeJVNFYnc9rQMVjfxmxmcVyHYb6j3ObcaCQdsNwnBByy1pXi6geR/Pudvcho4pDMYjMKnERGK105H8XisKUnEA5uWdec0rcxSsgoOMmhZBiBKSeGwES1bTr08lWW9jhrm1Bvafzt4Prbf2V
virt-8joqck.psf.osuosl.org,140.211.10.75 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP6rTw3oSG00LPCM60MxzvyvjQciIiVL8BHjP+0FlXMbL9bajkbgFo2i80Iw2UDfU9kScJ5dWjZi6QTt02S5Yo4=
virt-8joqck.psf.osuosl.org,140.211.10.75 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDzgiio5JRBdA10LIPuCpO8hNDIG96a8E0RH7A0UzW2R6Vw/pok2oRsUKBNZc3IJg86xWupOWvUcREodVsFz3fmNQhhHPbpC2SEviZ5l5B9mueNAIXzq0sQCe5vpXGQN9sZbsyTdqwUo1RZOxrRpSatSKN/Wj7RF0MA9GFoWIzQNCes94wjsmC1Y1UDL0OsRYlPBL30G8zSi0q13ez/4uMa9Xo1m+AT27SJtbVuJ3QGEJk+8yJitsi1uoSJhxwVJ6xwTLx+vmBfm8fZ0xXfcgCJpUD6gG0ZxXxQV9ZFqDJ8PVH82ncUFnV/3qQm8S+LL/OLxyUe9+kbujMNEfaxfebb
virt-et2yi0.psf.osuosl.org,140.211.10.71 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP6rTw3oSG00LPCM60MxzvyvjQciIiVL8BHjP+0FlXMbL9bajkbgFo2i80Iw2UDfU9kScJ5dWjZi6QTt02S5Yo4=
virt-et2yi0.psf.osuosl.org,140.211.10.71 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF0VGX5an53ta8KHe0G3/7tPEft9FE3/r+kgCHYECkhk
virt-et2yi0.psf.osuosl.org,140.211.10.71 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEDFo/Forit/e+kA/I+F4IuC6fUDybaeR0aIRpsV1pw6cgpum9rNHlGlYo8yTMr2IPT0k4Om2Z6oJly5BY8ZaaGlsWTo7OvGhe1ukstmFvXj9T3edCWCgPtoPWjFCTnDrs3GCLGXH22OCacl24mrcROTFmlZO7IjPLd18+WKVISdAXFcXutiV8+GZj3kk6hIlsHG/csdO8qMZdf0/hnFqkN0gfHJFzonj6vWYMFy1hXaVaPN7yzOJojNU0FVwDj8SDb8vldTSqJGtEPGPIr0DNVA0iMl73Oi6uCbplOSDTfE15O/HkG6ZfeiOTmP7e7TzVgs2lFVkOfoaVYR6X3LAH
virt-gwhg4e.psf.osuosl.org,140.211.10.76 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP6rTw3oSG00LPCM60MxzvyvjQciIiVL8BHjP+0FlXMbL9bajkbgFo2i80Iw2UDfU9kScJ5dWjZi6QTt02S5Yo4=
virt-gwhg4e.psf.osuosl.org,140.211.10.76 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvUykF+NDTAkxnieO6T6YuhZIyCBDGaLZhlJSQhdugydZFj9NooXK8scOnYPBKQ88C1mhIg6DbOBNUzMyl7oODmmDJZBrCzUjF1K7IFE9YrMsgSF5Q1+p+qoPhBp6x+8ZSEkaQof+8RqQmpRORHgDhHhD2U7DaKz6+XBoVm+JE4pOf9OxMcCRNKWT8Fncftwz8b5sGFsNXm+1p+7xNG9BXDKjSgXUM3V+bxWqm28YMbVr61o+Wrd0/y1ixZzD2idn3EcpChWgB/8hxRxMIh1DoA1vi512PxWNixtCokJMBTdsBbHGu/28AShN/vN0z1vjN54nJ+TzrMwJyejyKMvqP
virt-k4b2sa.psf.osuosl.org,140.211.10.80 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDEraq+pgWRiuW0TEay8UHmtNdbVy7QsIK9NJAuhI57PrV//24E+jHIcN58oNyY2XSEf8aivCjVDVBzCMNGC1oI=
virt-k4b2sa.psf.osuosl.org,140.211.10.80 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD3xSfKrd8G4wYl8Eu1r1x1Q/uZkO/s8kpCeFNLNgIMoDanNYJJJ1L3CTIwxOdBZmvJNxI0Nwcdopq2ylOgcEif4/lW1pbDoIEhL9vYORutKg41BjyAU46wi4XZ0v0KL8LavmA9qwgfdKAOZfNqiRXjB/YflMP14NbRjV/vOeTm0VbaCNa6DBF778iKRLjEhQfcHVvYBSMjIWIR9FVmx9Ga9qq6QPHJCM/gHcD6sZRwzbI0j2VU563H2+DSsxlqSl1xcCgg3Hi+U+JDdT8pj9kJeWtQcifiDo6CC5AwO726s9ayGTypWF2TyPsjskJo9WB8tJB6rUj60jObW3SGU8X
virt-sxw5uy.psf.osuosl.org,140.211.10.70 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP6rTw3oSG00LPCM60MxzvyvjQciIiVL8BHjP+0FlXMbL9bajkbgFo2i80Iw2UDfU9kScJ5dWjZi6QTt02S5Yo4=
virt-sxw5uy.psf.osuosl.org,140.211.10.70 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCo79Qu+lvxGDU4gn3ba3rqJ9UQUoBgd1dbhLkr7sPr0+JqAuZy8XVTDKvMAs3XN75EdD5qs1RiBLOgmPK6IQUPdObYzyDIeAIEHeIYsHNjtW+xCdw2cswqXfhsNs5ebC5aV56QIa5kHk7iLMbEF3/KEpkEs+zSufkYhVDZipoIjCrUmNHeL8Dl7kcTP7fCZgz0mVZf22VTv5lphAx1TK1qncFs094Zo4oliqgWTKoQtCJ0lR4bFVxi6Brf2q7aGHS2bBJEreuJ0RtiE3xB+5gLwZ0QnqEuNeiNjCexcVcZ/xfaC3cUKuwznZRQQMbAqnodlD8yg7w7ZdSMbvpBUUKD
virt-wdiwcy.psf.osuosl.org,140.211.10.78 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDEraq+pgWRiuW0TEay8UHmtNdbVy7QsIK9NJAuhI57PrV//24E+jHIcN58oNyY2XSEf8aivCjVDVBzCMNGC1oI=
virt-wdiwcy.psf.osuosl.org,140.211.10.78 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9IMAhp7CkvRZMBEMoIgjwxYFYw7ptHMR/OFum3mGV+JF9ZYeL6NxHavtkjuO6gJoo28n5w5QGgy39FCJsK3F87dLOrCT2IsSDmfIZoTg009yAE6DSkqQ2bmUOkQJG4avbRLZdyQktiFwPJVm5JhUsrqMwW8bRYrzO0FusU0PdHocIA75q+wrmkFdi+f6v5LiQNN8z3FJcl/SY0rimrDV/eRvgWyWoe949ujhZkODE5jrOO0mzYl4qNwC75CL4VsI3tu5OjDvvyao8VYxJ6VYyANHculrzvCdh6y7eqaaHc9VvRWVUK+xhvsW3Wgn7fjkOIlw7o6wnFZxl0/vBXUAV
virt-ys0nco.psf.osuosl.org,140.211.10.79 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDEraq+pgWRiuW0TEay8UHmtNdbVy7QsIK9NJAuhI57PrV//24E+jHIcN58oNyY2XSEf8aivCjVDVBzCMNGC1oI=
virt-ys0nco.psf.osuosl.org,140.211.10.79 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdk+TMPE+5l4nfyZ3inK5DHrazn7Zz0Z0YA+IwPD7xiv8Xr34z4VJZt8fdMPSIq7CDdQeda3gudA22omfOQtak5rg4sWQ8bYKsnDnguuJmCZZi3hBqldF73vI7W1LhrNUULPBtwYmW0MLoePFL/X7lNuaiZaCwJ7USQfQY+EnT7ZIsUb6fXLKzLAoe5Hy5V6A1XZ0cKTGXMMZi4nSs4V3icRxLrsp1/gWxu2c5oGUkZH0V2odCI9W/Le1EoaH9cTwjTKf+T5OkXWGVBzF4Vbr3IOpCWSkehxqsOagj/WnerBlrjczXyh4BPME+R8nR1xpUf+1VL04IJbToFOriAkat
```

I'll take a look and see what's to blame this evening.

**Comment by JulienPalard** [comment]
My generated file is 47 lines long and its sha256 starts with 5a1e798a (also leaving this for my if I try on other machines with maybe other version of ssh-keyscan).

@ewdurbin looks like you're only having virt-*, even though your scans on other machines have passed, which is strange, maybe just try a single one to start to diagnose:
```
$ ssh-keyscan docs.iad1.psf.io
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
docs.iad1.psf.io ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJpxnyt1Tri+0l6hQ5blehR9qTAKnO8Rva0uK913T2Eb72ueQhTQFqK4VHksS3Iy9wbR90dKv43ZfxzFKwCUB80RapZJw2e92xYRTpxHuFBWffQMOfrcQdMBWZgsa5SDz1chL7DPJIOwX4aw7xj+j5XjiPrw5aFEiXpQDjuDqtNcbWmCCTlTi2vaQAu2U6JbNihpZAMBe8ZsiiwMd5ZZkdXEXoZzFrHqnFv8Bhzl35aEjtwD8H6R84UpPUuxmUNjY09wo+eUFNLEmHSTErFvS/RUZ5nuOKVjvpV3AK1swqY8g7G95gjpyo6BoHA1MCoVvl/9b2WKdBG8De5cA9gf97
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
# docs.iad1.psf.io:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8
docs.iad1.psf.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDkX1wiIotOdjpzIFnImTsdx8YXy2Yini5jtJW9mUmlE
```

**Comment by bernhardreiter** [comment]
Just scanning from the outside would not be enough to verify the pubkeys. A person who has set up the machines should publish its pubkey(s).

**Pull request closed without merging**
