### PR TITLE
buildbot: Add release dashboard cache refresh request cronjob

### PR DESCRIPTION
**Pull request by zware**
## Description

- Restore the cache refresh request cronjob from the old host that was never properly added to Salt.

### CODE REVIEW

**Comment by zware** [comment]
cc: @encukou, @ambv

**Review by JacobCoffee — APPROVED** [review]

**Comment by JacobCoffee** [comment]
good to merge, @zware ? or were you waiting for feedback from the other two

**Comment by zware** [comment]
Nope, should be good to go; just wanted to make sure they're aware of it to avoid duplication of effort :)

**Comment by JacobCoffee** [comment]
should be live in 13 mins

**Pull request merged**
